# Generated by Django 4.1.7 on 2023-04-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_artiles_anons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='anons',
            field=models.CharField(max_length=250, verbose_name='Анонс'),
        ),
    ]
