# Generated by Django 4.1.7 on 2023-04-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_artiles_anons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
