# Generated by Django 4.1.7 on 2023-03-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(verbose_name='Модель авто')),
                ('marka', models.TextField(verbose_name='Марка авто')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('year', models.IntegerField(verbose_name='Год выпуска автомобиля')),
            ],
        ),
    ]
