# Generated by Django 4.1.7 on 2023-03-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av', '0005_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('marka', models.CharField(max_length=200)),
            ],
        ),
    ]
