# Generated by Django 4.1.7 on 2023-04-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('av', '0006_pars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pars',
        ),
    ]
